# Generated by Django 4.1.7 on 2023-03-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_pais_estado_cidade_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AddField(
            model_name='cidade',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
